### ISSUE TITLE
[PE-D] No Numbers for Pie Chart

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-1/tp#162]
While the pie chart is a useful feature, it is not useful as an "at a glance" way of viewing all the percentage information at once. This reduces its usefulness since you could have to use both the chart and the rate command to achieve the same functionality that the chart itself could have done.

![image.png](https://raw.githubusercontent.com/Yukun99/ped/main/files/3da081dc-716b-473c-8cb3-8845faa5d484.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Yukun99/ped#7

**Comment by LMAOboxhack** [comment]
UG states that numbers appear on hover.
